import enum
class E模式af8(enum.IntEnum):
	"""适用于：v8.0.7~8.0.13"""
	#xpath从1开始
	e运行状态 = 1
	e运行状态_总览 = 1
	e运行状态_安全运营中心 = 2
	e运行状态_业务安全 = 3
	e运行状态_用户安全 = 4
	e运行状态_流量会话 = 5
	e运行状态_流量会话_流量排行 = 1
	e运行状态_流量会话_异常流量 = 2
	e运行状态_流量会话_会话排行 = 3
	e运行状态_流量会话_流量管理状态 = 4
	e运行状态_封锁攻击者IP = 6
	e网络 = 2
	e网络_接口区域 = 1
	e网络_路由 = 2
	e网络_虚拟网线 = 3
	e网络_高级网络配置 = 4
	e网络_光口bypass设置 = 5
	e网络_IPSecVPN = 6
	e网络_IPSecVPN_DLAN运行状态 = 1
	e网络_IPSecVPN_基本设置 = 2
	e网络_IPSecVPN_用户管理 = 3
	e网络_IPSecVPN_连接管理 = 4
	e网络_IPSecVPN_虚拟IP池 = 5
	e网络_IPSecVPN_VPN接口设置 = 6
	e网络_IPSecVPN_多线路设置 = 7
	e网络_IPSecVPN_SDWAN智能选路 = 8
	e网络_IPSecVPN_本地子网列表 = 9
	e网络_IPSecVPN_隧道间路由设置 = 10
	e网络_IPSecVPN_第三方对接 = 11
	e网络_IPSecVPN_通用设置 = 12
	e网络_IPSecVPN_证书管理 = 13
	e网络_IPSecVPN_高级设置 = 14
	e对象 = 3
	e对象_网络对象 = 1
	e对象_服务 = 2
	e对象_安全策略模板 = 3
	e对象_安全防护规则库 = 4
	e对象_内容识别库 = 5
	e对象_IP地址库 = 6
	e对象_时间计划 = 7
	e对象_信任的证书颁发机构 = 8
	e策略 = 4
	e策略_地址转换 = 1
	e策略_访问控制 = 2
	e策略_安全策略 = 3
	e策略_解密 = 4
	e策略_流量管理 = 5
	e策略_配置向导 = 6
	e策略_黑白名单 = 7
	e策略_页面定制 = 8
	e系统 = 5
	e系统_系统配置 = 1
	e系统_管理员帐号 = 2
	e系统_系统维护 = 3
	e系统_排障 = 4
	e系统_高可用性 = 5
	e认证系统 = 6
	e认证系统_用户管理 = 1
	e认证系统_用户认证 = 2
	e认证系统_服务器访问认证 = 3
	e下一代安全防护体系 = 7
	e下一代安全防护体系_体系总览 = 1
	e下一代安全防护体系_EDR = 2
	e下一代安全防护体系_云端增值服务 = 3
	e下一代安全防护体系_安全防护能力 = 4
class C路径af8:
	"""适用于：v8.0.7~8.0.13"""
	c运行状态 = '//*[@id="ext-gen44"]'
	c运行状态_总览 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[1]/div[2]/div/ul/div/li[1]/div/a'
	c运行状态_安全运营中心 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[1]/div[2]/div/ul/div/li[2]/div/a'
	c运行状态_业务安全 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[1]/div[2]/div/ul/div/li[3]/div/a'
	c运行状态_业务安全_业务风险汇总 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[1]/a[2]/em/span/span'
	c运行状态_业务安全_攻击事件汇总 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[2]/a[2]/em/span/span'
	c运行状态_业务安全_实时漏洞分析 = 0
	c运行状态_用户安全 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[1]/div[2]/div/ul/div/li[4]/div/a'
	c运行状态_流量会话 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[1]/div[2]/div/ul/div/li[5]/div/a'
	c运行状态_流量会话_流量排行 = 1
	c运行状态_流量会话_异常流量 = 2
	c运行状态_流量会话_会话排行 = 3
	c运行状态_流量会话_流量管理状态 = 4
	c运行状态_封锁攻击者IP = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[1]/div[2]/div/ul/div/li[6]/div/a'
	c网络 = '//*[@id="ext-gen58"]'
	c网络_接口区域 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[2]/div[2]/div/ul/div/li[1]/div/a'
	c网络_接口区域_物理接口 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div[2]/div[1]/div[1]/ul/li[1]/a[2]/em/span/span'
	c网络_接口区域_子接口 = 0
	c网络_接口区域_VLAN接口 = 0
	c网络_接口区域_聚合接口 = 0
	c网络_接口区域_GRE隧道 = 0
	c网络_接口区域_区域 = 0
	c网络_接口区域_接口联动 = 0
	c网络_路由 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[2]/div[2]/div/ul/div/li[2]/div/a'
	c网络_路由_静态路由 = '//*[@id="ext-gen1015"]'
	c网络_路由_静态路由_IPv4 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[1]/div/div/div/div[1]/div[1]/ul/li[1]/a[2]/em/span/span'
	c网络_路由_静态路由_IPv6 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div[1]/div/div/div/div[1]/div[1]/ul/li[2]/a[2]/em/span/span'
	c网络_路由_策略路由 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[2]/a[2]/em/span/span'
	c网络_路由_多播路由 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[3]/a[2]/em/span/span'
	c网络_路由_OSPF = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[4]/a[2]/em/span/span'
	c网络_路由_RIP = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[5]/a[2]/em/span/span'
	c网络_路由_BGP = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[6]/a[2]/em/span/span'
	c网络_路由_查看路由 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[7]/a[2]/em/span/span'
	c网络_路由_路由测试 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[8]/a[2]/em/span/span'
	c网络_虚拟网线 = 3
	c网络_高级网络配置 = 4
	c网络_高级网络配置_ARP = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[1]/a[2]/em/span/span'
	c网络_高级网络配置_DNS = 0
	c网络_高级网络配置_DNS透明代理 = 0
	c网络_高级网络配置_DHCP = 0
	c网络_高级网络配置_SNMP = 0
	c网络_高级网络配置_TCPMSS = 0
	c网络_高级网络配置_HOSTS = 0
	c网络_光口bypass设置 = 5
	c网络_IPSecVPN = 6
	c网络_IPSecVPN_DLAN运行状态 = 1
	c网络_IPSecVPN_基本设置 = 2
	c网络_IPSecVPN_用户管理 = 3
	c网络_IPSecVPN_连接管理 = 4
	c网络_IPSecVPN_虚拟IP池 = 5
	c网络_IPSecVPN_VPN接口设置 = 6
	c网络_IPSecVPN_多线路设置 = 7
	c网络_IPSecVPN_SDWAN智能选路 = 8
	c网络_IPSecVPN_本地子网列表 = 9
	c网络_IPSecVPN_隧道间路由设置 = 10
	c网络_IPSecVPN_第三方对接 = 11
	c网络_IPSecVPN_通用设置 = 12
	c网络_IPSecVPN_证书管理 = 13
	c网络_IPSecVPN_高级设置 = 14
	c对象 = '//*[@id="ext-gen64"]'
	c对象_网络对象 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[3]/div[2]/div/ul/div/li[1]/div/a'
	c对象_网络对象_网络对象 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[1]/a[2]/em/span/span'
	c对象_网络对象_服务器识别 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[2]/a[2]/em/span/span'
	c对象_服务 = '/html/body/div[2]/div[1]/div[2]/div/div/div/div/div/div[3]/div[2]/div/ul/div/li[2]/div/a'
	c对象_服务_预定义服务 = '/html/body/div[2]/div[2]/div[2]/div/div/div/div/div/div/div/div/div[1]/div[1]/ul/li[1]/a[2]/em/span/span'
	c对象_服务_自定义服务 = 0
	c对象_服务_服务组 = 0
	c对象_安全策略模板 = 3
	c对象_安全防护规则库 = 4
	c对象_内容识别库 = 5
	c对象_IP地址库 = 6
	c对象_时间计划 = 7
	c对象_信任的证书颁发机构 = 8
	c策略 = '//*[@id="ext-gen70"]'
	c策略_地址转换 = 1
	c策略_访问控制 = 2
	c策略_安全策略 = 3
	c策略_解密 = 4
	c策略_流量管理 = 5
	c策略_配置向导 = 6
	c策略_黑白名单 = 7
	c策略_页面定制 = 8
	c系统 = '//*[@id="ext-gen76"]'
	c系统_系统配置 = 1
	c系统_管理员帐号 = 2
	c系统_系统维护 = 3
	c系统_排障 = 4
	c系统_高可用性 = 5
	c认证系统 = '//*[@id="ext-gen82"]'
	c认证系统_用户管理 = 1
	c认证系统_用户认证 = 2
	c认证系统_服务器访问认证 = 3
	c下一代安全防护体系 = '//*[@id="ext-gen88"]'
	c下一代安全防护体系_体系总览 = 1
	c下一代安全防护体系_EDR = 2
	c下一代安全防护体系_云端增值服务 = 3
	c下一代安全防护体系_安全防护能力 = 4
class C模式af8:
	"""只包含可进入的模式,层叠菜单不算
	适用于：v8.0.7~8.0.13"""
	c运行状态_总览 = (C路径af8.c运行状态, C路径af8.c运行状态_总览)
	c运行状态_安全运营中心 = (C路径af8.c运行状态, C路径af8.c运行状态_安全运营中心)
	c运行状态_业务安全 = (C路径af8.c运行状态, C路径af8.c运行状态_业务安全)
	c运行状态_用户安全 = (C路径af8.c运行状态, C路径af8.c运行状态_用户安全)
	c运行状态_流量会话_流量排行 = (C路径af8.c运行状态, C路径af8.c运行状态_流量会话, C路径af8.c运行状态_流量会话_流量排行)
	c运行状态_流量会话_异常流量 = (C路径af8.c运行状态, C路径af8.c运行状态_流量会话, C路径af8.c运行状态_流量会话_异常流量)
	c运行状态_流量会话_会话排行 = (C路径af8.c运行状态, C路径af8.c运行状态_流量会话, C路径af8.c运行状态_流量会话_会话排行)
	c运行状态_流量会话_流量管理状态 = (C路径af8.c运行状态, C路径af8.c运行状态_流量会话, C路径af8.c运行状态_流量会话_流量管理状态)
	c运行状态_封锁攻击者IP = (C路径af8.c运行状态, C路径af8.c运行状态_封锁攻击者IP)
	c网络_接口区域 = (C路径af8.c网络, C路径af8.c网络_接口区域)
	c网络_接口区域_物理接口 = (C路径af8.c网络, C路径af8.c网络_接口区域, C路径af8.c网络_接口区域_物理接口)
	c网络_接口区域_子接口 = (C路径af8.c网络, C路径af8.c网络_接口区域, C路径af8.c网络_接口区域_子接口)
	c网络_接口区域_VLAN接口 = (C路径af8.c网络, C路径af8.c网络_接口区域, C路径af8.c网络_接口区域_VLAN接口)
	c网络_接口区域_聚合接口 = (C路径af8.c网络, C路径af8.c网络_接口区域, C路径af8.c网络_接口区域_聚合接口)
	c网络_接口区域_GRE隧道 = (C路径af8.c网络, C路径af8.c网络_接口区域, C路径af8.c网络_接口区域_GRE隧道)
	c网络_接口区域_区域 = (C路径af8.c网络, C路径af8.c网络_接口区域, C路径af8.c网络_接口区域_区域)
	c网络_接口区域_接口联动 = (C路径af8.c网络, C路径af8.c网络_接口区域, C路径af8.c网络_接口区域_接口联动)
	c网络_路由 = (C路径af8.c网络, C路径af8.c网络_路由)
	c网络_路由_静态路由_IPv4 = (C路径af8.c网络, C路径af8.c网络_路由, C路径af8.c网络_路由_静态路由, C路径af8.c网络_路由_静态路由_IPv4)
	c网络_路由_静态路由_IPv6 = (C路径af8.c网络, C路径af8.c网络_路由, C路径af8.c网络_路由_静态路由, C路径af8.c网络_路由_静态路由_IPv6)
	c网络_路由_查看路由 = (C路径af8.c网络, C路径af8.c网络_路由, C路径af8.c网络_路由_查看路由)
	c网络_虚拟网线 = (C路径af8.c网络, C路径af8.c网络_虚拟网线)
	c网络_高级网络配置 = (C路径af8.c网络, C路径af8.c网络_高级网络配置)
	c网络_光口bypass设置 = (C路径af8.c网络, C路径af8.c网络_光口bypass设置)
	c网络_IPSecVPN_DLAN运行状态 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_DLAN运行状态)
	c网络_IPSecVPN_基本设置 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_基本设置)
	c网络_IPSecVPN_用户管理 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_用户管理)
	c网络_IPSecVPN_连接管理 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_连接管理)
	c网络_IPSecVPN_虚拟IP池 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_虚拟IP池)
	c网络_IPSecVPN_VPN接口设置 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_VPN接口设置)
	c网络_IPSecVPN_多线路设置 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_多线路设置)
	c网络_IPSecVPN_SDWAN智能选路 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_SDWAN智能选路)
	c网络_IPSecVPN_本地子网列表 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_本地子网列表)
	c网络_IPSecVPN_隧道间路由设置 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_隧道间路由设置)
	c网络_IPSecVPN_第三方对接 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_第三方对接)
	c网络_IPSecVPN_通用设置 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_通用设置)
	c网络_IPSecVPN_证书管理 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_证书管理)
	c网络_IPSecVPN_高级设置 = (C路径af8.c网络, C路径af8.c网络_IPSecVPN, C路径af8.c网络_IPSecVPN_高级设置)
